# Generated by Django 4.2.1 on 2023-06-11 03:27

from django.db import migrations


def seed_data(apps, schema_editor):
    User = apps.get_model("api", "User")
    User(email="farleyta@gmail.com").save()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_checkin_id_alter_intention_id_and_more"),
    ]

    operations = [migrations.RunPython(seed_data)]
