# Generated by Django 4.2.1 on 2023-06-11 14:03

from django.db import migrations


def seed_data(apps, schema_editor):
    IntentionSchedule = apps.get_model("api", "IntentionSchedule")
    # intention schedules cron schedules STORED IN UTC - this is daily at 8am EDT
    IntentionSchedule(cron_min=0, cron_hour=12).save()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_api"),
    ]

    operations = [migrations.RunPython(seed_data)]
