# Generated by Django 4.2.1 on 2023-06-11 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_seed_intention_schedule"),
    ]

    operations = []
