# Generated by Django 4.2.1 on 2023-06-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_modify_intention"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intention",
            name="user",
            field=models.ManyToManyField(related_name="intention", to="api.user"),
        ),
        migrations.AlterField(
            model_name="intentionschedule",
            name="cron_day_of_month",
            field=models.CharField(default="*", max_length=5),
        ),
        migrations.AlterField(
            model_name="intentionschedule",
            name="cron_day_of_week",
            field=models.CharField(default="*", max_length=5),
        ),
        migrations.AlterField(
            model_name="intentionschedule",
            name="cron_hour",
            field=models.CharField(default="*", max_length=5),
        ),
        migrations.AlterField(
            model_name="intentionschedule",
            name="cron_min",
            field=models.CharField(default="*", max_length=5),
        ),
        migrations.AlterField(
            model_name="intentionschedule",
            name="cron_month",
            field=models.CharField(default="*", max_length=5),
        ),
    ]
