# Generated by Django 4.2.1 on 2023-06-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_intention_user_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IntentionSchedule",
            new_name="Intention_Schedule",
        ),
        migrations.RemoveField(
            model_name="intention",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="intentions",
            field=models.ManyToManyField(related_name="user", to="api.intention"),
        ),
    ]
