# Generated by Django 4.2.1 on 2023-06-11 23:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_seed_intention"),
    ]

    operations = []
